### ISSUE TITLE
[Question] - How do you handle a second click whilst the door is still open/closing?

### ISSUE THREAD

**Issue by smanton** [andrewshilliday/garage-door-controller#114]
On my door when I hit the button a second time whilst it is opening or closing the door stops. Am I correct in assuming that in this scenario after a while the sensor will just report that door is in an open state and remain that way?

I started another project which used two sensors, one to indicate a fully closed state and one for a fully open state. Like many things I didn't quite finish it so was looking for something more polished.

**Comment by andrewshilliday** [comment]
Sorry for the delayed response.  If the door stops while opening, it will show an “open” status. The sensor is only aware of “closed” and “not closed”, so it takes an educated guess about “opening” or “closing” but those statuses should only last for about 15 seconds before it switches to “open” or “closed” depending on the sensor.
