### ISSUE TITLE
Authentication Through URL?

### ISSUE THREAD

**Issue by justsomeguy1983** [andrewshilliday/garage-door-controller#26]
Is there a way to modify the twisted portion of the code to allow authentication through the url?
E.G. http://user:password@xxx.xxx.xxx.xxx:8081
I've tried to change the code around but havent been successful in this,

Can someone who knows twisted help with this?
Thanks!

**Comment by andrewshilliday** [comment]
Not that I'm aware of.  However, you could just turn authentication off entirely.  If you are embedding the username and password in the URL, then you're not really being all that secure anyway.
