### ISSUE TITLE
Fresh Install - Left Image Broken

### ISSUE THREAD

**Issue by zbowman** [andrewshilliday/garage-door-controller#37]
Moving my garage controller from an older pi to a newer one. In the process, it looks like there's been some code changes since I first installed. Noticing there's username auth, email, and openhab support now. Awesome.

Downside, it looks like the default image for the left garage door isn't working. Only thing I did different from the tutorial is installed to /opt/garage-door-controller vs /~pi/garage-door-controller.

<img width="435" alt="screen shot 2016-09-25 at 10 13 09 pm" src="https://cloud.githubusercontent.com/assets/6321041/18820689/d46b2166-836d-11e6-9e2f-edd31a040e94.png">

**Comment by tynick** [comment]
Im experiencing the same thing.

**Comment by danb5** [comment]
Experiencing same issue and I did not change the install directory.  I have the broken left door icon and the status never updates.  It reads the correct status on boot up but then never updates unless rebooted.

**Comment by danb5** [comment]
I figured it out!  Disable open hub in the config.json.  Change it for true to false.

**Comment by andrewshilliday** [comment]
Thanks.  It must be throwing an error when if it attempts to connect to an openhab server that doesn't exist.  I'll see if there's an obvious way to get around that.  In the meantime, I've set the config.json to turn off openHab by default
