### ISSUE TITLE
CSS : RED, AMBER or GREEN  color instead of grey  color?

### ISSUE THREAD

**Issue by Gilles94500** [andrewshilliday/garage-door-controller#45]
Is there a way to update this CSS grey color so at a glance you know the status of your doors?
Ex : 
RED      when OPEN
AMBER when OPENING
GREEN when CLOSED

I have had a look at  http://demos.jquerymobile.com/1.4.5/icons/index.html but they say that the choice is between black and white.

Thanks
Gilles

**Comment by Gilles94500** [comment]
I have not been able to change the css jquerymobile background parameters, so I have used paint instead. I have added a green color to the  closed.png, a red color to the open.png and an amber color to the opening and closing png :)

Gilles

**Comment by andrewshilliday** [comment]
Gotcha.  Well I'm glad you figured out a solution. Can you attach the new icons?   I could push them into the master code as an option.

**Comment by Gilles94500** [comment]
Here you go.

**Comment by Gilles94500** [comment]
![opening](https://cloud.githubusercontent.com/assets/16894081/22149284/2edbf07a-df13-11e6-89c8-143ea71981e3.png)
![closed](https://cloud.githubusercontent.com/assets/16894081/22149282/2ed5d58c-df13-11e6-8109-72e3f4c5ee3c.png)
![closing](https://cloud.githubusercontent.com/assets/16894081/22149285/2ede7be2-df13-11e6-8d4b-1e0ad8d20339.png)
![open](https://cloud.githubusercontent.com/assets/16894081/22149283/2ed93006-df13-11e6-9eb9-cc098ecad404.png)

**Comment by andrewshilliday** [comment]
Thanks.  I'll see about adding a color option to the code and include these icons.
