### ISSUE TITLE
diagram minor bug in doc : wrong PIN Number: 21 instead of 27

### ISSUE THREAD

**Issue by Gilles94500** [andrewshilliday/garage-door-controller#49]
The diagram with the sensors and the wiring is wrong. The pin labelled 21 (between pin 17 and 22) where the LEFT sensor is connected to, should be 27. The other diagram is right.
I cannot update the diagram.

Thanks
Gilles

**Comment by andrewshilliday** [comment]
Thanks for pointing that out.  I think the easiest thing to do would be to just modify the config file to match the diagram.  I'll look into it.

**Comment by andrewshilliday** [comment]
Done.  I'm gonna close this ticket, but please check what I changed and confirm that it's consistent now.
