### ISSUE TITLE
Carbon monoxide input?

### ISSUE THREAD

**Issue by KenCab** [andrewshilliday/garage-door-controller#51]
I have this project up and running on my 2 door attached garage. thank you for creating it. I was all set to develop my own when I found yours. because my garage is attached to my house I would like to implement some kind of carbon monoxide safety interlock using an unused gpio and a CO detector that has a set of dry contacts. you know. just in case the dog steps on my key chain and accidentally hits the remote start. anyone know how I could make both doors open on a CO alarm? eventually even sms notifications.

**Comment by andrewshilliday** [comment]
That's not a bad idea and shouldn't be all that difficult.  As far as opening the garage door, you can write some script to monitor the unused gpio pin and simply call the garage door 'toggle button' command just by hitting the relevant URL (i.e. with curl). I can give you additional guidance if needed.
