### ISSUE TITLE
rename buttons

### ISSUE THREAD

**Issue by TrevorThebe** [andrewshilliday/garage-door-controller#54]
Hello,

Thank you very much for a great project. I am a designer with no coding knowledge but trying to learn as much as I can. I have enjoyed working with this project but need to rename my buttons. Thanks again and for a lovely project.

**Comment by andrewshilliday** [comment]
Thanks Trevor.

You can rename your buttons by changing them in the config.json file.   If you look towards the bottom of the file, you see lines like: 

`"name" : "LEFT",`
and 
`"name" : "RIGHT",`

You can change LEFT and RIGHT to be whatever you want.  That is what it will display in the web app.
