### ISSUE TITLE
Relay sleep timer not long enough

### ISSUE THREAD

**Issue by commputethis** [andrewshilliday/garage-door-controller#56]
First of all, thank you.  This is a really nice program.

When I connect the relay's to the garage door openers, the doors didn't open.  I could see the relay triggering, but didn't seem to be working.  I noticed in order to open my doors with the remote or the wall button I have to hold it for a moment.  I went in and modified controller.py to "fix" my issue.  I changed time.sleep under toggle_relay from 0.2 to 0.4 and it worked.

**Comment by andrewshilliday** [comment]
Glad to hear it.  I could make that into a configurable setting that goes into the config.json file, I suppose.  Has anyone else had this issue?
