### ISSUE TITLE
Won't open or close when other program is also used 

### ISSUE THREAD

**Issue by Jxck-S** [andrewshilliday/garage-door-controller#64]
I've got my rpi zero setup with this works fine but when I also use HAP-NodeJS when I open my door using HAP i can't use the web server after when I click it nothing happens rebooting fixes it but it happens again I believe is a gpio output conflict issue because it only happens when I've toggled it with HAP once. The other program is linked here https://github.com/legotheboss/YouTube-files/tree/master/Garage%20Solution/Sensor

**Comment by andrewshilliday** [comment]
I'm not sure exactly what you're problem is, but if you're running a second web server on the same rpi, then I suppose it could be possible that the servers are contending for the same port.  You can change the port of the garage door controller in the config.py

**Comment by Jxck-S** [comment]
I don't know what I was thinking, when I had this issue I was a noob. Crazy to look back in time at what I was doing.
