### ISSUE TITLE
pushover alert for specific device

### ISSUE THREAD

**Issue by flare04** [andrewshilliday/garage-door-controller#65]
Sometimes you only want alerts on a specific device

[config.json.patch.txt](https://github.com/andrewshilliday/garage-door-controller/files/1359244/config.json.patch.txt)
[controller.py.patch.txt](https://github.com/andrewshilliday/garage-door-controller/files/1359245/controller.py.patch.txt)

**Comment by andrewshilliday** [comment]
Not sure what you're trying to do exactly, but if you want to suggest a patch, create it in your own forked repo and then submit a pull request.
