### ISSUE TITLE
How to POST user/pass to http string

### ISSUE THREAD

**Issue by crockernr** [andrewshilliday/garage-door-controller#77]
Hi,
How to you pass the following with the user /password included?
http://"server":8081/clk?id="door" 

I'm attempting to integrate this into openHAB - Which I have working but have to disable security..

**Comment by lamping7** [comment]
Turn off the auth, disable remote access to the twisted server and use OpenHAB interface only: https://github.com/andrewshilliday/garage-door-controller/issues/69

**Comment by crockernr** [comment]
Thanks!
