### ISSUE TITLE
Different Authentication

### ISSUE THREAD

**Issue by budpi** [andrewshilliday/garage-door-controller#9]
Is there a way to prompt a number pad for the username and password. And, whilst on that note. Is there a way to just make a password and not a username?

Thanks!!!

**Comment by andrewshilliday** [comment]
Not that I know if (but I'll admit I didn't spend too much time on it)  The authentication is handled by the twisted python library.  If it is able to do password only authentication it should be easy to switch it over.  I'll take a look when I get a chance.
